version: '3.8'

services:
  mongodb:
    image: thuan410/db_mongdb
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  shopping_microservice:
    image: thuan410/be_shopping_microservice
    container_name: shopping_microservice
    ports:
      - "3003:3003" # Giả định port, bạn có thể thay đổi
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/shopping_db # Điều chỉnh tên database nếu cần
    networks:
      - app-network

  dashboard_microservice:
    image: thuan410/be_dashboard_microservice
    container_name: dashboard_microservice
    ports:
      - "3002:3002" # Giả định port, bạn có thể thay đổi
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/dashboard_db # Điều chỉnh tên database nếu cần
    networks:
      - app-network

  user_microservice:
    image: thuan410/be_user_microservice
    container_name: user_microservice
    ports:
      - "3001:3001" # Giả định port, bạn có thể thay đổi
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/user_db # Điều chỉnh tên database nếu cần
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: